### ISSUE TITLE
Incorrect gamma parameterization

### ISSUE THREAD

**Issue by jarad** [ksmzn/ShinyDistributionsApp#1]
In R, the gamma has 3rd argument rate, but you are inputing the [scale](https://github.com/ksmzn/ShinyDistributionsApp/blob/master/distributions.R#L52). Thus, when increasing the parameter in the app, the distribution shifts to the left, but should shift to the right with the pdf that you state. 

To maintain consistency with the exponential distribution, I suggest you just change the [gamma pdf](https://github.com/ksmzn/ShinyDistributionsApp/blob/master/ui.R#L401) to the version with the rate.

**Comment by ksmzn** [comment]
Sorry for the late reply.
I fixed it.
Thanks!
